### PR TITLE
Fixed issue, LICENSE not displaying on project.

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
As discussed in #4 , #5 , the MIT LICENSE wasn't displaying with the project, there was some issue made with the setup, I fixed the error now on the forked repository and you can merge it to your project, to fix the error for your project too.

Thanks,
Kendall Does Coding

### CODE REVIEW

**Comment by nairvarun** [comment]
i dont think that fixed it but thanks for bringing it to my attention

**Comment by KendallDoesCoding** [comment]
> i dont think that fixed it but thanks for bringing it to my attention

No problem, I tried it in my forked repo of your project and it worked so I created a pull request, but you anyway managed to fix it here too.

**Comment by nairvarun** [comment]
ye i deleted the old one and made a new license and it worked. idk its probably some weird bug

**Comment by KendallDoesCoding** [comment]
yeah

**Pull request merged**
